image: edbizarro/gitlab-ci-pipeline-php:8.0

cache:
  key: php8.0
  paths:
    - vendor/

stages:
  - Preparation
  - Static Analysis
#  - Testing
  - Build

composer:php8.0:
  stage: Preparation
  script:
    - composer global remove hirak/prestissimo
    - sudo composer self-update --2
    - which composer
    - which php
    - composer -V
    - php --version
    - sudo chown -R php:php .
    - php -d memory_limit=-1 /usr/bin/composer install --quiet

phpstan-analysis:php8.0:
  stage: Static Analysis
  script:
    - php -d memory_limit=-1 /usr/bin/composer phpstan-analysis
  when: on_success

phpmd-analysis:php8.0:
  stage: Static Analysis
  script:
    - php -d memory_limit=-1 /usr/bin/composer phpmd-analysis
  when: on_success

phpcpd-analysis:php8.0:
  stage: Static Analysis
  script:
    - vendor/bin/phpcpd --min-lines=3 --min-tokens=36 app/
  when: on_success

#phpunit:php8.0-feature:
#  stage: Testing
#  script:
#    - cp .env.example .env
#    - php artisan key:generate --env=testing
#    - php artisan test --env=testing --parallel tests/Feature
#  when: on_success

#phpunit:php8.0-livewire-a:
#  stage: Testing
#  script:
#    - cp .env.example .env
#    - php artisan key:generate --env=testing
#    - php artisan test --env=testing --parallel tests/Livewire/Cms/PartitionA
#  when: on_success

#phpunit:php8.0-livewire-b:
#  stage: Testing
#  script:
#    - cp .env.example .env
#    - php artisan key:generate --env=testing
#    - php artisan test --env=testing --parallel tests/Livewire/Cms/PartitionB
#  when: on_success

#phpunit:php8.0-livewire-c:
#  stage: Testing
#  script:
#    - cp .env.example .env
#    - php artisan key:generate --env=testing
#    - php artisan test --env=testing --parallel tests/Livewire/Cms/PartitionC
#  when: on_success

#phpunit:php8.0-unit:
#  stage: Testing
#  script:
#    - cp .env.example .env
#    - php artisan key:generate --env=testing
#    - php artisan test --env=testing --parallel tests/Unit
#  when: on_success

fpm-canary:
  image: docker:19.03.12
  stage: Build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - echo $DOCKER_SECRET > .passwd
    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$PROD_ENV --tag suitmedia/gopay-php-fpm:canary --file php-fpm.Dockerfile .
    - docker push suitmedia/gopay-php-fpm:canary
  only:
    - master
  when: on_success

fpm-release:
  image: docker:19.03.12
  stage: Build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - echo $DOCKER_SECRET > .passwd
    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$PROD_ENV --tag suitmedia/gopay-php-fpm:$CI_COMMIT_TAG --file php-fpm.Dockerfile .
    - docker push suitmedia/gopay-php-fpm:$CI_COMMIT_TAG
  only:
    - tags
  when: on_success

horizon-canary:
  image: docker:19.03.12
  stage: Build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - echo $DOCKER_SECRET > .passwd
    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$PROD_ENV --tag suitmedia/gopay-horizon:canary --file horizon.Dockerfile .
    - docker push suitmedia/gopay-horizon:canary
  only:
    - master
  when: on_success

horizon-release:
  image: docker:19.03.12
  stage: Build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - echo $DOCKER_SECRET > .passwd
    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$PROD_ENV --tag suitmedia/gopay-horizon:$CI_COMMIT_TAG --file horizon.Dockerfile .
    - docker push suitmedia/gopay-horizon:$CI_COMMIT_TAG
  only:
    - tags
  when: on_success

#horizon-dev:
#  image: docker:19.03.12
#  stage: Build
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - docker:19.03.12-dind
#  script:
#    - echo $DOCKER_SECRET > .passwd
#    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
#    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$STAGING_ENV --tag suitmedia/gopay-horizon:dev-latest --file horizon.Dockerfile .
#    - docker push suitmedia/gopay-horizon:dev-latest
#  only:
#    - master
#  when: on_success

#fpm-dev:
#  image: docker:19.03.12
#  stage: Build
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - docker:19.03.12-dind
#  script:
#    - echo $DOCKER_SECRET > .passwd
#    - cat .passwd | docker login --username $DOCKER_USERNAME --password-stdin
#    - docker build --build-arg SPATIE_USERNAME=$SPATIE_USERNAME --build-arg SPATIE_PASSWORD=$SPATIE_PASSWORD --build-arg LARAVEL_ENV=$STAGING_ENV --tag suitmedia/gopay-php-fpm:dev-latest --file php-fpm.Dockerfile .
#    - docker push suitmedia/gopay-php-fpm:dev-latest
#  only:
#    - master
#  when: on_success
